import type { COUNTRY_NAMES } from "./index";

export type Service = {
  // What kind of service do they provide?
  type: "Dispatch" | "Ambulance" | "Fire Department" | "Police";

  // What do they call themselves?
  name: string;

  // What do they do (in the user's language)?
  description?: string;

  // What is their phone number?
  phoneNumber: string;
};

export const SERVICES = {
  AL: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "17" },
    { type: "Fire Department", name: "Fire", phoneNumber: "18" },
    { type: "Police", name: "Police", phoneNumber: "19" },
  ],
  DZ: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "21606666" },
    { type: "Fire Department", name: "Fire", phoneNumber: "14" },
    { type: "Police", name: "Police", phoneNumber: "17" },
  ],
  AS: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "911" }],
  AD: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "118" },
    { type: "Fire Department", name: "Fire", phoneNumber: "118" },
    { type: "Police", name: "Police", phoneNumber: "110" },
  ],
  AO: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "118" },
    { type: "Fire Department", name: "Fire", phoneNumber: "118" },
    { type: "Police", name: "Police", phoneNumber: "110" },
  ],
  AG: [
    { type: "Dispatch", name: "Emergency Services", phoneNumber: "999" },
    { type: "Dispatch", name: "Emergency Services", phoneNumber: "911" },
  ],
  AR: [
    { type: "Police", name: "Police", phoneNumber: "101" },
    { type: "Ambulance", name: "Ambulance", phoneNumber: "107" },
    { type: "Fire Department", name: "Fire", phoneNumber: "101" },
  ],
  AM: [{ type: "Ambulance", name: "Ambulance", phoneNumber: "103" }],
  AW: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "911" }],
  AU: [
    {
      type: "Dispatch",
      name: "Emergency Services",
      description: "000 (112 on cell phone)",
      phoneNumber: "000",
    },
  ],
  AT: [
    { type: "Dispatch", name: "Emergency Services", phoneNumber: "112" },
    { type: "Ambulance", name: "Ambulance", phoneNumber: "122" },
  ],
  AZ: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "03" },
    { type: "Fire Department", name: "Fire", phoneNumber: "01" },
    { type: "Police", name: "Police", phoneNumber: "02" },
  ],
  BS: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "911" }],
  BH: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "999" }],
  BD: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "199" },
    { type: "Fire Department", name: "Fire", phoneNumber: "9555555" },
    { type: "Police", name: "Police", phoneNumber: "8665513" },
  ],
  BB: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "115" },
    { type: "Fire Department", name: "Fire", phoneNumber: "113" },
    { type: "Police", name: "Police", phoneNumber: "112" },
  ],
  BY: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "03" },
    { type: "Fire Department", name: "Fire", phoneNumber: "01" },
    { type: "Police", name: "Police", phoneNumber: "02" },
  ],
  BE: [
    {
      type: "Dispatch",
      name: "Emergency Services",
      description: "112 on cell phone",
      phoneNumber: "112",
    },
    { type: "Police", name: "Police", phoneNumber: "101" },
  ],
  BZ: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "911" }],
  BM: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "911" }],
  BT: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "110" },
    { type: "Fire Department", name: "Fire", phoneNumber: "112" },
    { type: "Police", name: "Police", phoneNumber: "113" },
  ],
  BO: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "911" }],
  BQ: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "911" }],
  BA: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "124" },
    { type: "Fire Department", name: "Fire", phoneNumber: "123" },
    { type: "Police", name: "Police", phoneNumber: "122" },
  ],
  BW: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "997" }],
  BR: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "911" }],
  VG: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "999" }],
  BN: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "991" },
    { type: "Fire Department", name: "Fire", phoneNumber: "995" },
    { type: "Police", name: "Police", phoneNumber: "993" },
  ],
  BG: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "150" },
    { type: "Fire Department", name: "Fire", phoneNumber: "160" },
    { type: "Police", name: "Police", phoneNumber: "166" },
  ],
  MM: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "999" }],
  KH: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "119" },
    { type: "Fire Department", name: "Fire", phoneNumber: "118" },
    { type: "Police", name: "Police", phoneNumber: "117" },
  ],
  CA: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "911" }],
  CV: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "130" },
    { type: "Fire Department", name: "Fire", phoneNumber: "131" },
    { type: "Police", name: "Police", phoneNumber: "132" },
  ],
  KY: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "911" }],
  TD: [
    { type: "Fire Department", name: "Fire", phoneNumber: "18" },
    { type: "Police", name: "Police", phoneNumber: "17" },
  ],
  CL: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "131" },
    { type: "Fire Department", name: "Fire", phoneNumber: "132" },
    { type: "Police", name: "Police", phoneNumber: "133" },
  ],
  CN: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "120" },
    { type: "Fire Department", name: "Fire", phoneNumber: "119" },
    { type: "Police", name: "Police", phoneNumber: "110" },
    { type: "Police", name: "Traffic Accident", phoneNumber: "122" },
  ],
  CO: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "119" }],
  CK: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "998" },
    { type: "Fire Department", name: "Fire", phoneNumber: "996" },
    { type: "Police", name: "Police", phoneNumber: "999" },
  ],
  CR: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "911" }],
  CI: [
    { type: "Fire Department", name: "Fire", phoneNumber: "110" },
    { type: "Police", name: "Police", phoneNumber: "180" },
  ],
  HR: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "112" }],
  CU: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "26811" }],
  CW: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "112" },
    { type: "Fire Department", name: "Fire", phoneNumber: "114" },
    { type: "Police", name: "Police", phoneNumber: "444444" },
  ],
  CY: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "112" }],
  CZ: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "112" },
    { type: "Fire Department", name: "Fire", phoneNumber: "150" },
    { type: "Police", name: "Police", phoneNumber: "158" },
  ],
  DK: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "112" }],
  DJ: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "351351" },
    { type: "Fire Department", name: "Fire", phoneNumber: "18" },
    { type: "Police", name: "Police", phoneNumber: "17" },
  ],
  DM: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "999" }],
  DO: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "911" }],
  TL: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "112" }],
  EC: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "131" },
    { type: "Police", name: "Police", phoneNumber: "101" },
  ],
  EG: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "123" },
    { type: "Fire Department", name: "Fire", phoneNumber: "180" },
    { type: "Police", name: "Police", phoneNumber: "122" },
  ],
  SV: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "911" }],
  EE: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "112" },
    { type: "Fire Department", name: "Fire", phoneNumber: "112" },
    { type: "Police", name: "Police", phoneNumber: "110" },
  ],
  ET: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "92" },
    { type: "Fire Department", name: "Fire", phoneNumber: "93" },
    { type: "Police", name: "Police", phoneNumber: "91" },
  ],
  FK: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "999" }],
  FJ: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "911" }],
  FI: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "112" }],
  FR: [
    { type: "Dispatch", name: "Emergency Services", phoneNumber: "112" },
    { type: "Ambulance", name: "Ambulance", phoneNumber: "15" },
    { type: "Fire Department", name: "Fire", phoneNumber: "18" },
    { type: "Police", name: "Police", phoneNumber: "17" },
  ],
  GF: [
    { type: "Dispatch", name: "Emergency Services", phoneNumber: "112" },
    { type: "Ambulance", name: "Ambulance", phoneNumber: "15" },
    { type: "Fire Department", name: "Fire", phoneNumber: "18" },
    { type: "Police", name: "Police", phoneNumber: "17" },
  ],
  PF: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "15" },
    { type: "Fire Department", name: "Fire", phoneNumber: "18" },
    { type: "Police", name: "Police", phoneNumber: "17" },
  ],
  GA: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "1300" },
    { type: "Fire Department", name: "Fire", phoneNumber: "18" },
    { type: "Police", name: "Police", phoneNumber: "1730" },
  ],
  GM: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "16" },
    { type: "Fire Department", name: "Fire", phoneNumber: "18" },
    { type: "Police", name: "Police", phoneNumber: "17" },
  ],
  GE: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "022" }],
  DE: [
    { type: "Dispatch", name: "Emergency Services", phoneNumber: "112" },
    { type: "Police", name: "Police", phoneNumber: "110" },
  ],
  GH: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "776111" },
    { type: "Fire Department", name: "Fire", phoneNumber: "192" },
    { type: "Police", name: "Police", phoneNumber: "999" },
  ],
  GI: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "999" }],
  GR: [
    { type: "Dispatch", name: "Emergency Services", phoneNumber: "112" },
    { type: "Ambulance", name: "Ambulance", phoneNumber: "166" },
    { type: "Fire Department", name: "Fire", phoneNumber: "199" },
    { type: "Police", name: "Police", phoneNumber: "100" },
  ],
  GD: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "434" },
    { type: "Fire Department", name: "Fire", phoneNumber: "112" },
    { type: "Police", name: "Police", phoneNumber: "911" },
  ],
  GP: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "18" },
    { type: "Fire Department", name: "Fire", phoneNumber: "18" },
    { type: "Police", name: "Police", phoneNumber: "17" },
  ],
  GU: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "911" }],
  GT: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "123" },
    { type: "Fire Department", name: "Fire", phoneNumber: "123" },
    { type: "Police", name: "Police", phoneNumber: "110" },
  ],
  GY: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "999" }],
  HT: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "118" },
    { type: "Police", name: "Police", phoneNumber: "114" },
  ],
  HN: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "195" },
    { type: "Fire Department", name: "Fire", phoneNumber: "198" },
    { type: "Police", name: "Police", phoneNumber: "119" },
  ],
  HK: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "999" }],
  HU: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "112" }],
  IS: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "112" }],
  IN: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "102" },
    { type: "Fire Department", name: "Fire", phoneNumber: "101" },
    { type: "Police", name: "Police", phoneNumber: "100" },
    {
      type: "Police",
      name: "Traffic Accident",
      phoneNumber: "103",
    },
  ],
  ID: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "118" },
    { type: "Fire Department", name: "Fire", phoneNumber: "113" },
    { type: "Police", name: "Police", phoneNumber: "110" },
  ],
  IR: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "115" },
    { type: "Fire Department", name: "Fire", phoneNumber: "123" },
    { type: "Police", name: "Police", phoneNumber: "110" },
  ],
  IE: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "112" }],
  IM: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "999" }],
  IL: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "101" },
    { type: "Fire Department", name: "Fire", phoneNumber: "102" },
    { type: "Police", name: "Police", phoneNumber: "100" },
  ],
  IT: [
    { type: "Dispatch", name: "Emergency Services", phoneNumber: "112" },
    { type: "Ambulance", name: "Ambulance", phoneNumber: "118" },
    { type: "Fire Department", name: "Fire", phoneNumber: "115" },
    { type: "Police", name: "Police", phoneNumber: "113" },
  ],
  JM: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "110" },
    { type: "Fire Department", name: "Fire", phoneNumber: "110" },
    { type: "Police", name: "Police", phoneNumber: "119" },
  ],
  JP: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "119" },
    { type: "Fire Department", name: "Fire", phoneNumber: "119" },
    { type: "Police", name: "Police", phoneNumber: "110" },
  ],
  JO: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "191" },
    { type: "Fire Department", name: "Fire", phoneNumber: "193" },
    { type: "Police", name: "Police", phoneNumber: "192" },
  ],
  KZ: [{ type: "Ambulance", name: "Ambulance", phoneNumber: "03" }],
  KE: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "999" }],
  KI: [{ type: "Ambulance", name: "Ambulance", phoneNumber: "994" }],
  XK: [{ type: "Ambulance", name: "Ambulance", phoneNumber: "94" }],
  KR: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "119" },
    { type: "Fire Department", name: "Fire", phoneNumber: "119" },
    { type: "Police", name: "Police", phoneNumber: "112" },
  ],
  KW: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "777" }],
  KG: [{ type: "Ambulance", name: "Ambulance", phoneNumber: "103" }],
  LV: [
    { type: "Dispatch", name: "Emergency Services", phoneNumber: "112" },
    { type: "Ambulance", name: "Ambulance", phoneNumber: "03" },
    { type: "Fire Department", name: "Fire", phoneNumber: "01" },
    { type: "Police", name: "Police", phoneNumber: "02" },
  ],
  LB: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "112" }],
  LS: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "121" },
    { type: "Fire Department", name: "Fire", phoneNumber: "122" },
    { type: "Police", name: "Police", phoneNumber: "123" },
  ],
  LR: [
    {
      type: "Dispatch",
      name: "Emergency Services",
      description: "911 (cell phones only)",
      phoneNumber: "911",
    },
  ],
  LY: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "193" }],
  LI: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "112" }],
  LT: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "112" }],
  LU: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "112" }],
  MO: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "999" }],
  MK: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "94" },
    { type: "Fire Department", name: "Fire", phoneNumber: "93" },
    { type: "Police", name: "Police", phoneNumber: "92" },
  ],
  MW: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "998" },
    { type: "Fire Department", name: "Fire", phoneNumber: "999" },
    { type: "Police", name: "Police", phoneNumber: "997" },
  ],
  MY: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "999" },
    { type: "Fire Department", name: "Fire", phoneNumber: "994" },
    { type: "Police", name: "Police", phoneNumber: "999" },
  ],
  MV: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "102" },
    { type: "Fire Department", name: "Fire", phoneNumber: "999" },
    { type: "Police", name: "Police", phoneNumber: "119" },
  ],
  ML: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "15" },
    { type: "Fire Department", name: "Fire", phoneNumber: "17" },
    { type: "Police", name: "Police", phoneNumber: "18" },
  ],
  MT: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "112" }],
  MP: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "911" }],
  MH: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "6254111" },
    { type: "Police", name: "Police", phoneNumber: "6258666" },
  ],
  MQ: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "15" },
    { type: "Fire Department", name: "Fire", phoneNumber: "18" },
    { type: "Police", name: "Police", phoneNumber: "17" },
  ],
  MR: [
    { type: "Fire Department", name: "Fire", phoneNumber: "118" },
    { type: "Police", name: "Police", phoneNumber: "117" },
  ],
  MU: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "999" }],
  MX: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "065" },
    { type: "Fire Department", name: "Fire", phoneNumber: "068" },
    { type: "Police", name: "Police", phoneNumber: "060" },
  ],
  MD: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "903" },
    { type: "Fire Department", name: "Fire", phoneNumber: "901" },
    { type: "Police", name: "Police", phoneNumber: "902" },
  ],
  MC: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "112" }],
  MN: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "103" },
    { type: "Fire Department", name: "Fire", phoneNumber: "101" },
    { type: "Police", name: "Police", phoneNumber: "102" },
  ],
  ME: [{ type: "Ambulance", name: "Ambulance", phoneNumber: "94" }],
  MS: [
    { type: "Dispatch", name: "Emergency Services", phoneNumber: "911" },
    { type: "Dispatch", name: "Emergency Services", phoneNumber: "999" },
  ],
  MA: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "15" },
    { type: "Fire Department", name: "Fire", phoneNumber: "15" },
    { type: "Police", name: "Police", phoneNumber: "19" },
  ],
  MZ: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "117" },
    { type: "Fire Department", name: "Fire", phoneNumber: "198" },
    { type: "Police", name: "Police", phoneNumber: "119" },
  ],
  NA: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "2032276" },
    { type: "Fire Department", name: "Fire", phoneNumber: "2032270" },
    { type: "Police", name: "Police", phoneNumber: "1011" },
  ],
  NP: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "228094" },
    { type: "Police", name: "Police", phoneNumber: "100" },
  ],
  NL: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "112" }],
  AN: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "112" }],
  NZ: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "111" }],
  NI: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "128" },
    { type: "Fire Department", name: "Fire", phoneNumber: "115" },
    { type: "Police", name: "Police", phoneNumber: "118" },
  ],
  NG: [{ type: "Ambulance", name: "Ambulance", phoneNumber: "199" }],
  NO: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "112" }],
  OM: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "999" }],
  PK: [{ type: "Ambulance", name: "Ambulance", phoneNumber: "15" }],
  PW: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "911" }],
  PS: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "101" },
    { type: "Fire Department", name: "Fire", phoneNumber: "101" },
    { type: "Police", name: "Police", phoneNumber: "100" },
  ],
  PA: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "2699778" },
    { type: "Fire Department", name: "Fire", phoneNumber: "103" },
    { type: "Police", name: "Police", phoneNumber: "104" },
  ],
  PG: [
    { type: "Fire Department", name: "Fire", phoneNumber: "110" },
    { type: "Police", name: "Police", phoneNumber: "000" },
  ],
  PY: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "00" }],
  PE: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "011" }],
  PH: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "166" }],
  PL: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "112" }],
  PT: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "112" }],
  PR: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "911" }],
  QA: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "999" }],
  RE: [
    { type: "Dispatch", name: "Emergency Services", phoneNumber: "112" },
    { type: "Ambulance", name: "Ambulance", phoneNumber: "15" },
    { type: "Fire Department", name: "Fire", phoneNumber: "18" },
    { type: "Police", name: "Police", phoneNumber: "17" },
  ],
  RO: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "112" }],
  RU: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "112" }],
  WS: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "999" }],
  SM: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "113" },
    { type: "Fire Department", name: "Fire", phoneNumber: "116" },
    { type: "Police", name: "Police", phoneNumber: "112" },
  ],
  SA: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "997" },
    { type: "Fire Department", name: "Fire", phoneNumber: "998" },
    { type: "Police", name: "Police", phoneNumber: "999" },
  ],
  RS: [{ type: "Ambulance", name: "Ambulance", phoneNumber: "94" }],
  SC: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "999" }],
  SL: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "999" },
    { type: "Fire Department", name: "Fire", phoneNumber: "019" },
    { type: "Police", name: "Police", phoneNumber: "999" },
  ],
  SG: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "995" },
    { type: "Fire Department", name: "Fire", phoneNumber: "995" },
    { type: "Police", name: "Police", phoneNumber: "999" },
  ],
  SK: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "155" },
    { type: "Fire Department", name: "Fire", phoneNumber: "150" },
    { type: "Police", name: "Police", phoneNumber: "158" },
  ],
  SI: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "112" }],
  SB: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "911" }],
  ZA: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "10177" },
    { type: "Fire Department", name: "Fire", phoneNumber: "10177" },
    { type: "Police", name: "Police", phoneNumber: "10111" },
  ],
  ES: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "112" }],
  LK: [
    {
      type: "Dispatch",
      name: "Emergency Services",
      phoneNumber: "1691095",
    },
  ],
  SH: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "911" }],
  KN: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "911" }],
  LC: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "999" }],
  SX: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "911" },
    { type: "Fire Department", name: "Fire", phoneNumber: "911" },
    { type: "Police", name: "Police", phoneNumber: "911" },
  ],
  VC: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "999" }],
  SE: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "112" }],
  CH: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "144" },
    { type: "Fire Department", name: "Fire", phoneNumber: "118" },
    { type: "Police", name: "Police", phoneNumber: "117" },
  ],
  SY: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "110" },
    { type: "Fire Department", name: "Fire", phoneNumber: "113" },
    { type: "Police", name: "Police", phoneNumber: "112" },
  ],
  TW: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "119" },
    { type: "Fire Department", name: "Fire", phoneNumber: "119" },
    { type: "Police", name: "Police", phoneNumber: "110" },
  ],
  TJ: [{ type: "Ambulance", name: "Ambulance", phoneNumber: "03" }],
  TZ: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "112" }],
  TH: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "191" },
    { type: "Fire Department", name: "Fire", phoneNumber: "199" },
    { type: "Police", name: "Police", phoneNumber: "191" },
  ],
  TG: [{ type: "Police", name: "Police", phoneNumber: "101" }],
  TO: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "911" }],
  TT: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "990" },
    { type: "Fire Department", name: "Fire", phoneNumber: "990" },
    { type: "Police", name: "Police", phoneNumber: "999" },
  ],
  TN: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "190" },
    { type: "Fire Department", name: "Fire", phoneNumber: "198" },
    { type: "Police", name: "Police", phoneNumber: "197" },
  ],
  TR: [
    { type: "Dispatch", name: "Emergency Services", phoneNumber: "112" },
    { type: "Ambulance", name: "Ambulance", phoneNumber: "101" },
    { type: "Fire Department", name: "Fire", phoneNumber: "102" },
    { type: "Police", name: "Police", phoneNumber: "100" },
  ],
  TM: [{ type: "Ambulance", name: "Ambulance", phoneNumber: "03" }],
  TC: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "999" }],
  TV: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "911" }],
  UG: [
    {
      type: "Dispatch",
      name: "Emergency Services",
      description: "112 (cell phone), 999 (fixed)",
      phoneNumber: "112",
    },
  ],
  UA: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "03" },
    { type: "Fire Department", name: "Fire", phoneNumber: "01" },
    { type: "Police", name: "Police", phoneNumber: "02" },
  ],
  AE: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "998" }],
  GB: [
    { type: "Dispatch", name: "Emergency Services", phoneNumber: "112" },
    { type: "Dispatch", name: "Emergency Services", phoneNumber: "999" },
  ],
  US: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "911" }],
  UY: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "999" }],
  VI: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "911" }],
  UZ: [{ type: "Ambulance", name: "Ambulance", phoneNumber: "03" }],
  VU: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "112" }],
  VA: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "113" },
    { type: "Fire Department", name: "Fire", phoneNumber: "115" },
    { type: "Police", name: "Police", phoneNumber: "112" },
  ],
  VE: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "171" }],
  VN: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "05" },
    { type: "Fire Department", name: "Fire", phoneNumber: "08" },
    { type: "Police", name: "Police", phoneNumber: "03" },
  ],
  EH: [{ type: "Ambulance", name: "Ambulance", phoneNumber: "150" }],
  YE: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "191" },
    { type: "Fire Department", name: "Fire", phoneNumber: "191" },
    { type: "Police", name: "Police", phoneNumber: "194" },
  ],
  ZM: [{ type: "Dispatch", name: "Emergency Services", phoneNumber: "999" }],
  ZW: [
    { type: "Ambulance", name: "Ambulance", phoneNumber: "994" },
    { type: "Fire Department", name: "Fire", phoneNumber: "993" },
    { type: "Police", name: "Police", phoneNumber: "995" },
  ],
} satisfies Partial<Record<keyof typeof COUNTRY_NAMES, Service[]>>;
