export const DEFAULT_COUNTRY = "US";

export const COUNTRY_NAMES = {
  AF: "Afghanistan",
  AX: "Aland Islands",
  AL: "Albania",
  DZ: "Algeria",
  AS: "American Samoa",
  AD: "Andorra",
  AO: "Angola",
  AI: "Anguilla",
  AQ: "Antarctica",
  AG: "Antigua and Barbuda",
  AR: "Argentina",
  AM: "Armenia",
  AW: "Aruba",
  AU: "Australia",
  AT: "Austria",
  AZ: "Azerbaijan",
  BS: "Bahamas",
  BH: "Bahrain",
  BD: "Bangladesh",
  BB: "Barbados",
  BY: "Belarus",
  BE: "Belgium",
  BZ: "Belize",
  BJ: "Benin",
  BM: "Bermuda",
  BT: "Bhutan",
  BO: "Bolivia",
  BQ: "Bonaire, Sint Eustatius and Saba",
  BA: "Bosnia and Herzegovina",
  BW: "Botswana",
  BV: "Bouvet Island",
  BR: "Brazil",
  IO: "British Indian Ocean Territory",
  BN: "Brunei",
  BG: "Bulgaria",
  BF: "Burkina Faso",
  BI: "Burundi",
  KH: "Cambodia",
  CM: "Cameroon",
  CA: "Canada",
  CV: "Cape Verde",
  KY: "Cayman Islands",
  CF: "Central African Republic",
  TD: "Chad",
  CL: "Chile",
  CN: "China",
  CX: "Christmas Island",
  CC: "Cocos (Keeling) Islands",
  CO: "Colombia",
  KM: "Comoros",
  CG: "Congo",
  CD: "Democratic Republic of Congo",
  CK: "Cook Islands",
  CR: "Costa Rica",
  CI: "Côte d'Ivoire",
  HR: "Croatia",
  CU: "Cuba",
  CW: "Curaçao",
  CY: "Cyprus",
  CZ: "Czechia",
  DK: "Denmark",
  DJ: "Djibouti",
  DM: "Dominica",
  DO: "Dominican Republic",
  EC: "Ecuador",
  EG: "Egypt",
  SV: "El Salvador",
  GQ: "Equatorial Guinea",
  ER: "Eritrea",
  EE: "Estonia",
  ET: "Ethiopia",
  FK: "Falkland Islands",
  FO: "Faroe Islands",
  FJ: "Fiji",
  FI: "Finland",
  FR: "France",
  GF: "French Guiana",
  PF: "French Polynesia",
  TF: "French Southern Territories",
  GA: "Gabon",
  GM: "Gambia",
  GE: "Georgia",
  DE: "Germany",
  GH: "Ghana",
  GI: "Gibraltar",
  GR: "Greece",
  GL: "Greenland",
  GD: "Grenada",
  GP: "Guadeloupe",
  GU: "Guam",
  GT: "Guatemala",
  GG: "Guernsey",
  GN: "Guinea",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HT: "Haiti",
  HM: "Heard Island and McDonald Mcdonald Islands",
  VA: "Vatican City",
  HN: "Honduras",
  HK: "Hong Kong",
  HU: "Hungary",
  IS: "Iceland",
  IN: "India",
  ID: "Indonesia",
  IR: "Iran",
  IQ: "Iraq",
  IE: "Ireland",
  IM: "Isle of Man",
  IL: "Israel",
  IT: "Italy",
  JM: "Jamaica",
  JP: "Japan",
  JE: "Jersey",
  JO: "Jordan",
  KZ: "Kazakhstan",
  KE: "Kenya",
  KI: "Kiribati",
  XK: "Kosovo",
  KP: "North Korea",
  KR: "South Korea",
  KW: "Kuwait",
  KG: "Kyrgyzstan",
  LA: "Laos",
  LV: "Latvia",
  LB: "Lebanon",
  LS: "Lesotho",
  LR: "Liberia",
  LY: "Libya",
  LI: "Liechtenstein",
  LT: "Lithuania",
  LU: "Luxembourg",
  MO: "Macao",
  MK: "North Macedonia",
  MG: "Madagascar",
  MW: "Malawi",
  MY: "Malaysia",
  MV: "Maldives",
  ML: "Mali",
  MT: "Malta",
  MH: "Marshall Islands",
  MQ: "Martinique",
  MR: "Mauritania",
  MU: "Mauritius",
  YT: "Mayotte",
  MX: "Mexico",
  FM: "Micronesia",
  MD: "Moldova",
  MC: "Monaco",
  MN: "Mongolia",
  ME: "Montenegro",
  MS: "Montserrat",
  MA: "Morocco",
  MZ: "Mozambique",
  MM: "Myanmar",
  NA: "Namibia",
  NR: "Nauru",
  NP: "Nepal",
  NL: "Netherlands",
  AN: "Netherlands Antilles",
  NC: "New Caledonia",
  NZ: "New Zealand",
  NI: "Nicaragua",
  NE: "Niger",
  NG: "Nigeria",
  NU: "Niue",
  NF: "Norfolk Island",
  MP: "Northern Mariana Islands",
  NO: "Norway",
  OM: "Oman",
  PK: "Pakistan",
  PW: "Palau",
  PS: "Palestine",
  PA: "Panama",
  PG: "Papua New Guinea",
  PY: "Paraguay",
  PE: "Peru",
  PH: "Philippines",
  PN: "Pitcairn",
  PL: "Poland",
  PT: "Portugal",
  PR: "Puerto Rico",
  QA: "Qatar",
  RE: "Réunion",
  RO: "Romania",
  RU: "Russia",
  RW: "Rwanda",
  BL: "Saint Barthélemy",
  SH: "Saint Helena, Ascension and Tristan da Cunha",
  KN: "Saint Kitts and Nevis",
  LC: "Saint Lucia",
  MF: "Saint Martin (French part)",
  PM: "Saint Pierre and Miquelon",
  VC: "Saint Vincent and the Grenadines",
  WS: "Samoa",
  SM: "San Marino",
  ST: "Sao Tome and Principe",
  SA: "Saudi Arabia",
  SN: "Senegal",
  RS: "Serbia",
  SC: "Seychelles",
  SL: "Sierra Leone",
  SG: "Singapore",
  SX: "Sint Maarten (Dutch part)",
  SK: "Slovakia",
  SI: "Slovenia",
  SB: "Solomon Islands",
  SO: "Somalia",
  ZA: "South Africa",
  GS: "South Georgia and the South Sandwich Islands",
  SS: "South Sudan",
  ES: "Spain",
  LK: "Sri Lanka",
  SD: "Sudan",
  SR: "Suriname",
  SJ: "Svalbard and Jan Mayen",
  SZ: "Eswatini",
  SE: "Sweden",
  CH: "Switzerland",
  SY: "Syria",
  TW: "Taiwan",
  TJ: "Tajikistan",
  TZ: "Tanzania",
  TH: "Thailand",
  TL: "East Timor",
  TG: "Togo",
  TK: "Tokelau",
  TO: "Tonga",
  TT: "Trinidad and Tobago",
  TN: "Tunisia",
  TR: "Turkey",
  TM: "Turkmenistan",
  TC: "Turks and Caicos Islands",
  TV: "Tuvalu",
  UG: "Uganda",
  UA: "Ukraine",
  AE: "United Arab Emirates",
  GB: "United Kingdom",
  US: "United States",
  UM: "United States Minor Outlying Islands",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VU: "Vanuatu",
  VE: "Venezuela",
  VN: "Vietnam",
  VG: "Virgin Islands, British",
  VI: "Virgin Islands, U.S.",
  WF: "Wallis and Futuna",
  EH: "Western Sahara",
  YE: "Yemen",
  ZM: "Zambia",
  ZW: "Zimbabwe",
};

export const COUNTRY_ALT_NAMES: Partial<
  Record<keyof typeof COUNTRY_NAMES, string[]>
> = {
  AE: ["UAE", "Emirates"],
  AX: ["Åland Islands"],
  BA: ["Bosnia"],
  BF: ["Upper Volta"],
  BL: ["St Barts", "St. Barts", "Saint Barthelemy"],
  BN: ["Brunei Darussalam"],
  BR: ["Brasil"],
  BS: ["The Bahamas"],
  BY: ["Byelorussia", "Belorussia", "White Russia"],
  CC: ["Keeling Islands"],
  CD: ["DRC", "Congo-Kinshasa", "Zaire", "Democratic Republic of the Congo"],
  CF: ["CAR"],
  CG: ["Republic of Congo", "Congo-Brazzaville"],
  CH: ["Schweiz", "Suisse", "Svizzera", "Helvetia", "Swiss Confederation"],
  CI: ["Ivory Coast", "Cote d'Ivoire", "Cote dIvoire"],
  CN: ["PRC", "People's Republic of China"],
  CV: ["Cabo Verde"],
  CW: ["Curacao"],
  CZ: ["Czech Republic"],
  DE: ["Deutschland", "Federal Republic of Germany"],
  EE: ["Eesti"],
  ES: ["España", "Espana"],
  ET: ["Abyssinia"],
  FI: ["Suomi"],
  FK: ["Islas Malvinas", "Malvinas"],
  FM: ["Federated States of Micronesia", "FSM"],
  FO: ["Faeroe Islands", "Faeroes"],
  GB: [
    "United Kingdom",
    "UK",
    "England",
    "Great Britain",
    "Scotland",
    "Northern Ireland",
    "Wales",
  ],
  GM: ["The Gambia"],
  GR: ["Hellas", "Hellenic Republic"],
  HK: ["HK"],
  HR: ["Hrvatska"],
  HU: ["Magyarország", "Magyarorszag"],
  IE: ["Republic of Ireland", "Éire", "Eire"],
  IR: ["Persia"],
  IT: ["Italia"],
  JP: ["Nihon", "Nippon"],
  KH: ["Kampuchea"],
  KN: ["St Kitts and Nevis", "St. Kitts and Nevis"],
  KP: ["DPRK", "Democratic People's Republic of Korea"],
  KR: ["Korea", "Republic of Korea"],
  LA: ["Lao PDR", "Lao People's Democratic Republic"],
  LC: ["St Lucia", "St. Lucia"],
  LK: ["Ceylon"],
  LU: ["Luxemburg"],
  MD: ["Moldavia", "Republic of Moldova"],
  ME: ["Crna Gora"],
  MF: ["St Martin", "St. Martin"],
  MK: ["Macedonia", "FYROM", "Former Yugoslav Republic of Macedonia"],
  MM: ["Burma"],
  MO: ["Macau"],
  NA: ["South West Africa"],
  NL: ["Holland"],
  NZ: ["Aotearoa"],
  PF: ["Tahiti"],
  PG: ["PNG"],
  PH: ["Pilipinas"],
  PL: ["Polska"],
  PM: ["St Pierre and Miquelon", "St. Pierre and Miquelon"],
  RE: ["Reunion"],
  RO: ["Rumania", "Roumania"],
  RU: ["Russian Federation"],
  SE: ["Sverige"],
  SH: ["St Helena", "St. Helena"],
  SX: ["St Maarten", "St. Maarten"],
  SZ: ["Swaziland"],
  TH: ["Siam"],
  TL: ["Timor-Leste"],
  TR: ["Türkiye", "Turkiye"],
  TW: ["Republic of China", "ROC", "Formosa"],
  US: ["USA", "America", "United States of America"],
  VA: ["Holy See"],
  VC: ["St Vincent", "St. Vincent and the Grenadines"],
  VG: ["BVI", "British Virgin Islands"],
  VI: ["USVI", "US Virgin Islands"],
  VN: ["Viet Nam"],
  VU: ["New Hebrides"],
  WS: ["Western Samoa"],
  ZM: ["Northern Rhodesia"],
  ZW: ["Rhodesia"],
};
